# Generated by Django 2.0.5 on 2018-08-26 05:07

import appis.user.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=220, verbose_name='密码')),
                ('type', models.SmallIntegerField(choices=[(0, '黑名单用户'), (1, '普通用户'), (2, 'VIP用户')], verbose_name='用户类型')),
                ('status', models.NullBooleanField(default=True, verbose_name='账号状态')),
                ('face', models.ImageField(default='def_face.jpg', upload_to=appis.user.models.face_upload, verbose_name='头像')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=220, verbose_name='token信息')),
                ('update_time', models.DateTimeField(default=datetime.datetime(2018, 8, 26, 5, 7, 36, 411318, tzinfo=utc), verbose_name='更新时间')),
                ('user_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserInfo')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
