# Generated by Django 2.0.5 on 2018-08-26 05:07

import appis.kuukann.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=appis.kuukann.models.img_upload, verbose_name='图片')),
                ('tiny_img', models.ImageField(upload_to=appis.kuukann.models.tiny_img_upload, verbose_name='缩略图')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2018, 8, 26, 5, 7, 36, 413313, tzinfo=utc), verbose_name='创建时间')),
                ('status', models.NullBooleanField(default=True, verbose_name='状态')),
                ('user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserInfo', verbose_name='所属用户')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
